name: CI
on: [push, pull_request]
jobs:
    project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Run formatting
              run: bun format
              continue-on-error: true
            - name: Run linting
              run: bun lint
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: cd into backend
              run: cd backend

            - name: Install dependencies
              run: bun install

            - name: Compile code
              run: bun run build

            - name: Run tests
              run: bun test
            